### ISSUE TITLE
Feature 1: User can view a list of all spells

### ISSUE THREAD

**Issue by TristanChao** [TristanChao/front-end-project#1]
## ⚙️ Feature

> ##### What capability will users have when this feature is merged?

User can view a complete list of all spells.

## 📐 Functionality

> ##### A description of how the application will work from the perspective of the user.

Users can scroll through a page of spell cards.

## 🖼️ Wireframes

> ##### Wireframe screenshot(s) of what the app should look like when it is complete.

![image](https://github.com/user-attachments/assets/1cae772c-8700-4288-a923-9f83c3ab5d95)

## ✅ Task List

> ##### Commit checklist for tasks needed to complete the feature.

- [x] Create a basic navbar.
- [x] Create a header.
- [x] Create a main div to hold the spell list view.
- [x] Create a div to hold the spell cards.
- [x] Create a CSS class named 'row' with properties display: flex and flex-wrap: wrap, then apply the class to the spell card div.
- [x] Create interfaces for the various objects retrieved from the API.
- [x] Query the API for the basic spell data and store it in a variable named `spellData`.
- [ ] Create a function named `renderCard` with two parameters: name of type string and level of type number
  - [x] Create a main card div
    - [x] Create a CSS class named 'card'
      - background-color: #FFF9EB;
      - border-radius: 5px;
      - border: 1px solid #F5E8CC;
      - box-shadow: 2px 4px 4px;
    - [x] Apply the card class to the main card div
  - [x] Create a div for the spell level
    - [x] Create a span and add text content based on the `level` parameter
  - [x] Create a div for the spell circle image
    - [x] Create a CSS class named 'spell-circle-div'
      - [x] width and height properties of 90px by default
  - [x] Create an image element for the spell circle
    - [x] Write a function to apply a random spell circle image url to the image element
    - [x] Write css to make the image width 100% of the div
  - [x] Create a div for the spell name, write css to make the contents centered horizontally and vertically
    - [x] Use the `name` parameter to fill the spell name
  - [x] Append all elements into the appropriate parents
  - [x] Append the card into the spell cards div
- [x] Loop through the `spellData.results` array and append a card for each spell.
- **Clean Up**
  - [x] Remove all buttons and placeholders that do not serve the functionality of the feature.
  - [x] Remove all console logs.
  - [x] Remove all commented out code.
  - [x] Remove all CSS properties that have no effect.
  - [x] Check all code for proper formatting and indentation.
  - [x] Confirm that there are no errors in the console while using the application.
  - [x] Confirm that all previous functionality still works without errors.
  - [x] Confirm that the user interface looks natural on both mobile and desktop screens.
  - [ ] Create GIFs of the feature being used on both mobile and desktop screen sizes for inclusion in Pull Request.
