### ISSUE TITLE
Feature 2: User can view the details of each spell.

### ISSUE THREAD

**Issue by TristanChao** [TristanChao/front-end-project#2]
## ⚙️ Feature

> ##### What capability will users have when this feature is merged?

View the details of a spell.

## 📐 Functionality

> ##### A description of how the application will work from the perspective of the user.

When the user clicks on a card, the view will change and display the details of the spell.

## 🖼️ Wireframes

> ##### Wireframe screenshot(s) of what the app should look like when it is complete.

![image](https://github.com/user-attachments/assets/6281377b-bfa1-447c-b8f0-632d5a5e8206)

## ✅ Task List

> ##### Commit checklist for tasks needed to complete the feature.

- [x] Create a new view for the spell details.
- [x] Create an anchor element with an event listener that will switch back to the spells list view when clicked.
- [x] Create placeholder elements for the details.
- [x] Write an event listener that will get the data-url property of the card that was clicked.
  - [x] Use the url to query the API for the spell's details.
  - [x] Fill the text content of the placeholders with spell details.
- [x] Add scroll visuals?
- **Clean Up**
  - [x] Remove all buttons and placeholders that do not serve the functionality of the feature.
  - [x] Remove all console logs.
  - [x] Remove all commented out code.
  - [x] Remove all CSS properties that have no effect.
  - [x] Check all code for proper formatting and indentation.
  - [x] Confirm that there are no errors in the console while using the application.
  - [x] Confirm that all previous functionality still works without errors.
  - [x] Confirm that the user interface looks natural on both mobile and desktop screens.
  - [x] Create GIFs of the feature being used on both mobile and desktop screen sizes for inclusion in Pull Request.
