### ISSUE TITLE
Feature 3: User can sort the spells list by name and level.

### ISSUE THREAD

**Issue by TristanChao** [TristanChao/front-end-project#3]
## ⚙️ Feature

> ##### What capability will users have when this feature is merged?

User can choose whether to sort the spells list by name or level.

## 📐 Functionality

> ##### A description of how the application will work from the perspective of the user.

The user can select options on a dropdown which will change the sort order of the spell cards.

## 🖼️ Wireframes

> ##### Wireframe screenshot(s) of what the app should look like when it is complete.

![image](https://github.com/user-attachments/assets/5ea86f03-387d-4a77-bc03-b77874485bc7)
![image](https://github.com/user-attachments/assets/2c9575ab-2591-41b3-a88f-280dbab0f250)

## ✅ Task List

> ##### Commit checklist for tasks needed to complete the feature.

- [x] Create a label for the sort dropdown.
- [x] Create a dropdown element with two options - name and level.
- [x] Write code that will store the spell information in a new object divided by level.
- [x] Write an event listener for the dropdown that listens for when the input is changed.
  - [x] When the input is changed, clear the spell cards and re-render them in the appropriate sort order.
  - [x] For sorting by name, I can use the same code as the initial rendering.
    - [x] Place the initial rendering in a function so it can be reused.
  - [x] For sorting by level, loop through the new spells by level object and render the cards in that order.
- **Clean Up**
  - [x] Remove all buttons and placeholders that do not serve the functionality of the feature.
  - [x] Remove all console logs.
  - [x] Remove all commented out code.
  - [x] Remove all CSS properties that have no effect.
  - [x] Check all code for proper formatting and indentation.
  - [x] Confirm that there are no errors in the console while using the application.
  - [x] Confirm that all previous functionality still works without errors.
  - [x] Confirm that the user interface looks natural on both mobile and desktop screens.
  - [x] Create GIFs of the feature being used on both mobile and desktop screen sizes for inclusion in Pull Request.
