### ISSUE TITLE
Feature 4: User can search on the spell list and filter by various criteria.

### ISSUE THREAD

**Issue by TristanChao** [TristanChao/front-end-project#4]
## ⚙️ Feature

> ##### What capability will users have when this feature is merged?

User can search for partial or whole terms and the spells list will filter to include spells that match the search term. The user can also fill out an advanced filter to search by additional criteria.

## 📐 Functionality

> ##### A description of how the application will work from the perspective of the user.

The user can search spells by filling out a search bar at the top of the page. If they click on the advanced filter button, it will open a modal with a form for the additional criteria, then filter the spells list and update it.

## 🖼️ Wireframes

> ##### Wireframe screenshot(s) of what the app should look like when it is complete.

![image](https://github.com/user-attachments/assets/6aff810f-aa17-43c9-829d-848c6bba89cb)

## ✅ Task List

> ##### Commit checklist for tasks needed to complete the feature.

- [x] Create a new object to store sort/search/filter information.
- [x] Create a form object for the search bar.
- [x] Create an input element and a submit button within the form.
- [x] when the form is submitted, store the values in the sort object
- [x] Create a button that will open the form modal.
- [x] Create a dialog with a form.
  - [x] The form has 3 options: name, level, school
  - [x] name is an input
  - [x] level is a dropdown
  - [x] school is a dropdown
- [x] create a new array to store the list of filtered cards
- [x] create a new div to store the filtered list of cards
- [x] create a function to filter the card array
  - [x] query the api using the appropriate filters
  - [x] render cards and append them to the filtered card array
  - [x] clear the div of filtered cards
  - [x] append the filtered array to the div
- [x] when the filter form is submitted
  - [x] store the form values
  - [x] if the values are not the default, filter the cards
  - [x] hide the all cards list and show the filtered cards list
- [x] when the filter values are reset
  - [x] hide the filtered list and show the all cards list
- **Clean Up**
  - [x] Remove all buttons and placeholders that do not serve the functionality of the feature.
  - [x] Remove all console logs.
  - [x] Remove all commented out code.
  - [x] Remove all CSS properties that have no effect.
  - [x] Check all code for proper formatting and indentation.
  - [x] Confirm that there are no errors in the console while using the application.
  - [x] Confirm that all previous functionality still works without errors.
  - [x] Confirm that the user interface looks natural on both mobile and desktop screens.
  - [x] Create GIFs of the feature being used on both mobile and desktop screen sizes for inclusion in Pull Request.
