### ISSUE TITLE
Feature 5: User can create spellbooks.

### ISSUE THREAD

**Issue by TristanChao** [TristanChao/front-end-project#5]
## ⚙️ Feature

> ##### What capability will users have when this feature is merged?

Create a new spellbook with options for class.

## 📐 Functionality

> ##### A description of how the application will work from the perspective of the user.

The user will fill out a small form which includes a spellbook name and optional class information, then a new spellbook will be created for them.

## 🖼️ Wireframes

> ##### Wireframe screenshot(s) of what the app should look like when it is complete.

![image](https://github.com/user-attachments/assets/cc7d9753-052b-4948-8252-0eb8d7146816)
![image](https://github.com/user-attachments/assets/ac080e4d-3045-44bf-9624-0e1e68b3cb7e)

## ✅ Task List

> ##### Commit checklist for tasks needed to complete the feature.

- [x] create a menu that includes an option to create a new spellbook
- [x] for desktop view, add a 'new spellbook' button to the navbar with the same functionality
- [x] create a new view with a form for spellbook creation
  - [x] name input
  - [x] optional class select
  - [x] class level select - hidden by default
  - [x] spellcasting modifier select - hidden by default
  - [x] cancel and save buttons
- [x] create an event listener for when the class select input is changed that will show the hidden select elements when the value is not falsy
- [x] create an object that will change the spellcasting modifier depending on what class is selected
- [x] create a new data object to store spellbook information in local storage
  - [x] an array of objects representing the information about a spellbook and the spells that are included
  - [x] spellbook information: spellbook name, class name, class level, and spellcasting ability modifier
- [x] create read and write functions for local storage
- **Clean Up**
  - [x] Remove all buttons and placeholders that do not serve the functionality of the feature.
  - [x] Remove all console logs.
  - [x] Remove all commented out code.
  - [x] Remove all CSS properties that have no effect.
  - [x] Check all code for proper formatting and indentation.
  - [x] Confirm that there are no errors in the console while using the application.
  - [x] Confirm that all previous functionality still works without errors.
  - [x] Confirm that the user interface looks natural on both mobile and desktop screens.
  - [x] Create GIFs of the feature being used on both mobile and desktop screen sizes for inclusion in Pull Request.
