### ISSUE TITLE
Feature 6: User can view spellbooks.

### ISSUE THREAD

**Issue by TristanChao** [TristanChao/front-end-project#6]
## ⚙️ Feature

> ##### What capability will users have when this feature is merged?

Users can open up their spellbooks to see the collection of spells in them.

## 📐 Functionality

> ##### A description of how the application will work from the perspective of the user.

## 🖼️ Wireframes

> ##### Wireframe screenshot(s) of what the app should look like when it is complete.

![image](https://github.com/user-attachments/assets/e14c8cb6-90a2-498e-aa12-8106d1b9d3bd)
![image](https://github.com/user-attachments/assets/3cd0eb90-3a5d-44d3-9c6e-8ffb99f7b1a2)

## ✅ Task List

> ##### Commit checklist for tasks needed to complete the feature.

- [x] write a function to render a spellbook `anchor`
  - [x] render a `div` with a class of `spellbook-link-div`
  - [x] render an `anchor`
    - [x] class of `spellbook-link`
    - [x] text content is the spellbook name
    - [x] `data-id` attribute with spellbook id
- [x] the function should be looped for each of the existing spellbooks upon loading
- [x] the function should be called whenever a new spellbook is created
- [x] add a spellbook property to the `cardSort` object that will store the name of whatever spellbook is being displayed
- [x] update the filter spell function to filter for the spells in the current spellbook
- [x] add an event listener to the `div` holding the spellbook `anchor`s
  - [x] add a guard clause to only continue if the target is an `anchor`
  - [x] update the `cardSort` spellbook property with the name of the event target
  - [x] call the filter function
  - [x] update the header with the name of the spellbook
    - [x] for desktop view, if there is a class and level, add those as well
- **Clean Up**
  - [x] Remove all buttons and placeholders that do not serve the functionality of the feature.
  - [x] Remove all console logs.
  - [x] Remove all commented out code.
  - [x] Remove all CSS properties that have no effect.
  - [x] Check all code for proper formatting and indentation.
  - [x] Confirm that there are no errors in the console while using the application.
  - [x] Confirm that all previous functionality still works without errors.
  - [x] Confirm that the user interface looks natural on both mobile and desktop screens.
  - [x] Create GIFs of the feature being used on both mobile and desktop screen sizes for inclusion in Pull Request.
