### ISSUE TITLE
Feature 7: User can edit and delete spellbooks.

### ISSUE THREAD

**Issue by TristanChao** [TristanChao/front-end-project#7]
## ⚙️ Feature

> ##### What capability will users have when this feature is merged?

User can edit the details of their spellbook as well as delete them.

## 📐 Functionality

> ##### A description of how the application will work from the perspective of the user.

The user can click a setting icon to pull up a menu that includes two options: edit spellbook and delete spellbook.
Editing the spellbook will bring them to the form view where they can modify values and update the information.
Deleting the spellbook will first bring up a confirmation box then delete the spellbook if they confirm.

## 🖼️ Wireframes

> ##### Wireframe screenshot(s) of what the app should look like when it is complete.

## ✅ Task List

> ##### Commit checklist for tasks needed to complete the feature.

HTML
- [x] create a settings button that will appear when a spellbook is being viewed
- [x] create a dialog with 3 buttons
  - [x] edit spellbook
  - [x] delete spellbook
  - [x] close
- [x] create a dialog for the delete confirmation
  - [x] "are you sure you want to delete [spellbook name]?"
  - [x] cancel button
  - [x] confirm button

TS
- [x] write code that will show the settings button if a spellbook is being shown
- [x] add an event listener to the settings button that will open the dialog as a modal when clicked
- [x] add an event listener for the edit spellbook button being clicked
  - [x] set the spellbookData.editing property to the spellbook name
  - [x] close the modal
  - [x] prepopulate the spellbook form with the spellbook details, then switch to its view
- [x] update the spellbook form submit event
  - [x] add a conditional to check for the spellbookData.editing id
  - [x] update spellbookData and write to local storage
- [x] add an event listener for the delete spellbook button being clicked
  - [x] close the settings modal
  - [x] open the confirmation modal
- [x] add an event listener for the cancel delete button being clicked that will close the modal
- [x] add an event listener for the confirm delete button being clicked
  - [x] close the modal
  - [x] delete the spellbook from spellbookData
  - [x] write to local storage
- [x] add an event listener for the close settings button that will close the modal
- **Clean Up**
  - [ ] Remove all buttons and placeholders that do not serve the functionality of the feature.
  - [ ] Remove all console logs.
  - [ ] Remove all commented out code.
  - [ ] Remove all CSS properties that have no effect.
  - [ ] Check all code for proper formatting and indentation.
  - [ ] Confirm that there are no errors in the console while using the application.
  - [ ] Confirm that all previous functionality still works without errors.
  - [ ] Confirm that the user interface looks natural on both mobile and desktop screens.
  - [ ] Create GIFs of the feature being used on both mobile and desktop screen sizes for inclusion in Pull Request.
