### ISSUE TITLE
Feature 8: User can manage spells in their spellbooks.

### ISSUE THREAD

**Issue by TristanChao** [TristanChao/front-end-project#8]
## ⚙️ Feature

> ##### What capability will users have when this feature is merged?

User can manage the spells in their spellbook.

## 📐 Functionality

> ##### A description of how the application will work from the perspective of the user.

The user can enter a 'manage spells' mode from the spellbook page where they can toggle whether a spell is included in their spellbook.

## 🖼️ Wireframes

> ##### Wireframe screenshot(s) of what the app should look like when it is complete.

![image](https://github.com/user-attachments/assets/89bdcfe4-01fa-4c3c-99e0-7401b7432fbf)
![image](https://github.com/user-attachments/assets/bc4fe351-cdd2-42e5-9c23-f24b8808b83b)

## ✅ Task List

> ##### Commit checklist for tasks needed to complete the feature.

HTML
- [x] create a manage spells button that appears when a spellbook is being displayed and the page is wide enough (5 card columns)
- [x] add a button to the spellbook settings that does the same as the manage spells button
- [x] add a 'save' button next to the spellbook settings button that appears when a spellbook is being managed

CSS
- [x] create two rulesets for the classes on the toggleInclude buttons to vary the styling

TS
- [x] add a property to the cardSort object that represents the spellbook being actively managed
- [x] update the render card function to add a button to the top div
  - the same button will toggle between adding and removing a spell
  - [x] default classes: toggleInclude, hidden, add
  - [x] data-include = 'false'
- [x] update the filter spells function
  - [x] separate spellbook filtering and spellbook management filtering (or set one to null when the other is given a value)
  - [x] if the spellbook has a class, query for class spells and display the whole list
  - [x] if it doesn't, just display all the spells
- [x] add an event listener to the two manage spells buttons
  - [x] show the save button
  - [x] hide the settings button
  - [x] reset filters
  - [x] set the sort order to level
  - [x] set cardSort.spellbook to null
  - [x] set cardSort.managing to the spellbook name and id being managed
  - [x] loop through cardsArray
    - [x] show the toggleInclude button
    - [x] check if the spell name is included in the spellbook
      - [x] if it is, remove the add class from the toggleInclude button and add the remove class, then set the data-include attribute to 'true'
      - [x] if it isn't, set the spell circle image brightness to 0
  - [x] call filterSpellsList
- [x] add an event listener to the cards div (if there isn't one already)
  - [x] if the target is the toggleInclude button
    - [x] get the nearest card div ancestor
    - [x] check its data-include attribute
      - [x] if it was false
        - [x] remove add class and add remove class
        - [x] set the spell circle image brightness to 1
        - [x] push the spell name to the spellbook's spells array
      - [x] if it was true
        - [x] add add class and remove remove class
        - [x] set spell circle image brightness to 0
        - [x] get the index of the spell's name in the spellbook's spells array and splice it out
    - [x] call writeData
- [x] add an event listener to the save button being clicked
  - [x] hide the save button
  - [x] show the settings button
  - [x] reset filters
  - [x] set the sort order to level
  - [x] set cardSort.spellbook to the spellbook name and id that was being managed
  - [x] set cardSort.managing to null
  - [x] loop through cardsArray
    - [x] set the brightness of the spell circle images to 1
  - [x] call filterSpellsList
- **Clean Up**
  - [x] Remove all buttons and placeholders that do not serve the functionality of the feature.
  - [x] Remove all console logs.
  - [x] Remove all commented out code.
  - [x] Remove all CSS properties that have no effect.
  - [x] Check all code for proper formatting and indentation.
  - [x] Confirm that there are no errors in the console while using the application.
  - [x] Confirm that all previous functionality still works without errors.
  - [x] Confirm that the user interface looks natural on both mobile and desktop screens.
  - [x] Create GIFs of the feature being used on both mobile and desktop screen sizes for inclusion in Pull Request.
